name: Configure Production Environment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm install
      - run: npm run build

      - name: Update client_id configuration
        uses: jossef/action-set-json-field@v1
        with:
          file: build/static/config.json
          field: client_id
          value: ${{ secrets.client_id }}

      - name: Update client_secret configuration
        uses: jossef/action-set-json-field@v1
        with:
          file: build/static/config.json
          field: client_secret
          value: ${{ secrets.client_secret }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: upload to artifact
          path: |
            build
            !build/**/*.md
